"""Fresh integration checks through the LIVE engine graph and a local broker.

Unlike unit tests that call flow methods on hand-built stubs, these tests build
TradingEngine in live-only mode, use its real strategy/runtime/execution,
position, fill-routing and SL components, and replace only the broker with the
deterministic in-memory implementation. All persistence is isolated in tmp_path.
"""
import json
import threading
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from types import SimpleNamespace

from core.market_status import EngineStatus, MarketState
from core.trade_close import TradeCloseManager
from core.timeframe_engine import Bar
from execution.live.broker_client import StubLiveBroker
from execution.models import OrderState
from execution.live.order_watcher import OrderWatcher
from execution.live.poller import LiveBrokerPoller
from persistence.manager import PersistenceManager
from portfolio.position_manager import Position, PositionSide
from strategies.types import PendingEntry, SignalType
from trading_engine import TradingEngine


class _FundedStubBroker(StubLiveBroker):
    def __init__(self, *, defer_fills=False):
        super().__init__(gate_enabled=True, defer_fills=defer_fills)
        self._net_positions = {}
        self._position_strategies = {}

    def place_market_order(self, side, quantity, instrument, **kwargs):
        result = super().place_market_order(
            side=side, quantity=quantity, instrument=instrument, **kwargs)
        if result.get("status") == "filled":
            signed = int(quantity) if str(side).upper() == "BUY" else -int(quantity)
            self._net_positions[instrument] = self._net_positions.get(instrument, 0) + signed
        return result

    def ack_order(self, broker_order_id, price=None):
        rec = self._orders.get(broker_order_id)
        was_filled = bool(rec and rec.get("status") == "filled")
        ok = super().ack_order(broker_order_id, price=price)
        if ok and rec and not was_filled and rec.get("status") == "filled":
            signed = int(rec.get("filled_quantity") or rec.get("quantity") or 0)
            if str(rec.get("side")).upper() == "SELL":
                signed = -signed
            instrument = rec.get("instrument")
            self._net_positions[instrument] = self._net_positions.get(instrument, 0) + signed
            # Correlation IDs are generated by the engine, so the integration
            # fixture keeps the strategy mapping for broker-position checks.
            self._position_strategies[instrument] = "gold_02"
        return ok

    def ack_partial_order(self, broker_order_id, quantity, price=None):
        """Materialize a broker-confirmed partial fill for stress scenarios."""
        rec = self._orders.get(broker_order_id)
        if not rec or rec.get("status") != "submitted":
            return False
        if not StubLiveBroker.ack_order(self, broker_order_id, price=price):
            return False
        quantity = int(quantity)
        if quantity <= 0 or quantity >= int(rec.get("quantity") or 0):
            raise ValueError("partial fill quantity must be between 0 and order quantity")
        rec["filled_quantity"] = quantity
        rec["average_fill_price"] = float(price or rec.get("price") or 0.0)
        for fill in self._fills.values():
            if fill.get("broker_order_id") == broker_order_id:
                fill["quantity"] = quantity
                fill["filled_quantity"] = quantity
        signed = quantity if str(rec.get("side")).upper() == "BUY" else -quantity
        instrument = rec.get("instrument")
        self._net_positions[instrument] = self._net_positions.get(instrument, 0) + signed
        self._position_strategies[instrument] = "gold_02"
        return True

    def positions(self):
        return [{"strategy_id": self._position_strategies.get(instrument, "gold_02"),
                 "instrument": instrument,
                 "side": "LONG" if quantity > 0 else "SHORT",
                 "quantity": abs(quantity)}
                for instrument, quantity in self._net_positions.items() if quantity]

    def account_status(self):
        return {"mode": "LIVE", "equity": 10_000_000.0,
                "available_margin": 10_000_000.0, "used_margin": 0.0}


def _runtime(tmp_path, *, quantity=1, broker=None):
    root = Path(__file__).resolve().parents[1]
    config = json.loads((root / "config" / "live_settings.json").read_text())
    for key, filename in (
        ("live_db_path", "live.db"),
        ("live_state_path", "live-state.json"),
        ("db_path", "paper.db"),
        ("state_path", "paper-state.json"),
    ):
        config["system"][key] = str(tmp_path / filename)
    config["live"]["broker"] = "stub"
    config["live"]["gate"] = "ON"
    config["live"]["live_trading_enabled"] = True
    config["live"]["rollover"]["state_path"] = str(tmp_path / "rollover.json")
    config["strategies"] = {
        "gold_02": dict(config["strategies"]["gold_02"], quantity=quantity),
    }
    config_path = tmp_path / "config.json"
    config_path.write_text(json.dumps(config))

    engine = TradingEngine(config_path=str(config_path), live_only=True)
    env = engine.live
    sid = "gold_02"
    broker = broker or _FundedStubBroker()
    env.broker = broker
    env.execution_engine.broker = broker
    persistence = PersistenceManager(
        state_path=str(tmp_path / "live-state.json"),
        db_path=str(tmp_path / "live.db"),
    )
    engine.set_persistence(persistence, env_name="live")
    env.trade_close_manager = TradeCloseManager(
        position_manager=env.position_manager,
        pnl_engines=env.pnl_engines,
        account_engines=env.account_engines,
        global_account=env.account_engine,
        risk_engine=env.risk_engine,
        persistence=persistence,
        event_store=env.event_store,
        telegram=engine.telegram,
        event_callback=engine._event_callback,
        trade_ledger=env.trade_ledger,
    )
    engine._reconciled_envs.add("live")
    # EnvMarketStatus delegates the session state to its own wrapped instance.
    # LIVE-only wiring may rebind engine.market_status after env creation, so
    # force the exact base object used by the environment's admission check.
    (getattr(env.market_status, "_base", None) or env.market_status).force_state(
        MarketState.LIVE_TRADING)
    env.market_status.set_engine_status(EngineStatus.TRADING)
    env.market_status.mark_rest_data_fresh()
    engine.market_data_health.record_tick("GOLDM", time.time())
    env.account_engines[sid].set_broker_reported(
        equity=10_000_000, available_margin=10_000_000, used_margin=0)
    return engine, env, broker, persistence


def _live_price(engine, env, broker, price):
    engine.market_data_health.record_tick("GOLDM", time.time())
    broker.update_price("GOLDM", price)
    env.execution_engine.update_price("GOLDM", price)


def _long_candle_signal(engine, env, broker, strategy, *, start=1, high=103,
                        low=99, previous_low=98):
    strategy._prev_fast_close = 100.0
    strategy._prev_htf_value = 100.0
    strategy._prev_fast_high = high - 1
    strategy._prev_fast_low = previous_low
    _live_price(engine, env, broker, 101.0)
    signal = strategy.on_bar(
        Bar("GOLDM", "15m", start, start + 1, 100, high, low, 101, 1),
        SimpleNamespace(htf_value=100.0), 100.0)
    assert signal is not None
    assert signal.metadata["trigger_state"] == "ARMED"
    return signal


def _watcher(engine, env, broker, failures=None):
    return OrderWatcher(
        engine=env.execution_engine,
        broker=broker,
        config=engine.config,
        clock=time.time,
        quote_fn=lambda instrument: broker._prices.get(instrument),
        strategy_lookup=lambda sid: env.strategies.get(sid),
        position_lookup=lambda sid, instrument: next((p for p in
            env.position_manager.get_positions_by_strategy(sid)
            if p.is_open and p.instrument == instrument), None),
        on_failure_event=(failures.append if failures is not None else None),
        on_fills=lambda fills: [engine._handle_fill(
            fill, fill.entry_signal_id, env_name="live") for fill in fills],
        on_order=lambda order, signal: engine._persist_order(
            order, signal, env_name="live"),
    )


def _fire_and_submit(engine, env, broker, strategy, signal, price=None):
    engine._process_signal(signal, "live")
    trigger = float(signal.trigger_price)
    _live_price(engine, env, broker,
                trigger if price is None else float(price))
    fired = strategy.on_tick(trigger if price is None else float(price), time.time())
    assert fired is signal
    engine._process_signal(fired, "live")
    return list(env.execution_engine._orders.values())[-1]


def test_fresh_candle_trigger_entry_reversal_and_sl_full_runtime_cycle(tmp_path):
    engine, env, broker, persistence = _runtime(tmp_path)
    strategy = env.strategies["gold_02"]
    reversal_alerts = []
    engine.telegram.on_reversal_complete = reversal_alerts.append
    try:
        # Actual DEMA crossover rule on an actual completed Bar creates only
        # an armed signal; no broker order may exist before the LTP crossing.
        strategy._prev_fast_close = 100.0
        strategy._prev_htf_value = 100.0
        strategy._prev_fast_high = 102.0
        strategy._prev_fast_low = 98.0
        _live_price(engine, env, broker, 101.0)
        entry = strategy.on_bar(
            Bar("GOLDM", "15m", 1, 2, 100, 103, 99, 101, 1),
            SimpleNamespace(htf_value=100.0), 100.0)
        assert entry is not None
        assert entry.metadata["trigger_state"] == "ARMED"
        assert entry.metadata["signal_candle_high"] == 103.0
        assert entry.metadata["signal_htf_dema_atr"] == 100.0
        engine._process_signal(entry, "live")
        assert not env.execution_engine._orders

        # The actual strategy tick handler fires the candle's high exactly
        # once; processing that fired signal traverses the engine's real
        # order manager, broker router, fill flow, position book and SL flow.
        assert strategy.on_tick(102.99, time.time()) is None
        fired_entry = strategy.on_tick(103.0, time.time())
        assert fired_entry is entry
        assert strategy.on_tick(104.0, time.time()) is None
        engine._process_signal(fired_entry, "live")
        entry_orders = list(env.execution_engine._orders.values())
        assert len(entry_orders) == 1
        assert entry_orders[0].state == OrderState.FILLED
        assert entry_orders[0].quantity == 1
        old_position = env.position_manager.open_positions[0]
        assert old_position.stop_price == 98.0
        assert old_position.sl_state == "ARMED"
        assert env.sl_monitor.armed_ids() == [old_position.position_id]

        # An actual opposite DEMA crossover arms a paired reversal. It cannot
        # fire on the candle itself; its live tick submits the old-position
        # exit first. Broker-flat confirmation then activates the paired entry.
        strategy._prev_fast_close = 100.0
        strategy._prev_htf_value = 100.0
        strategy._prev_fast_high = 103.0
        strategy._prev_fast_low = 99.0
        _live_price(engine, env, broker, 99.0)
        reversal_exit = strategy.on_bar(
            Bar("GOLDM", "15m", 3, 4, 100, 101, 96, 99, 1),
            SimpleNamespace(htf_value=100.0), 100.0)
        assert reversal_exit is not None
        assert reversal_exit.metadata["pending_trigger_kind"] == "REVERSAL_EXIT"
        paired_entry = strategy.pending_entry.signal
        engine._process_signal(reversal_exit, "live")
        assert len(env.execution_engine._orders) == 1

        _live_price(engine, env, broker, reversal_exit.trigger_price)
        fired_exit = strategy.on_tick(reversal_exit.trigger_price, time.time())
        assert fired_exit is reversal_exit
        engine._process_signal(fired_exit, "live")

        orders = list(env.execution_engine._orders.values())
        assert [o.order_role for o in orders] == ["ENTRY", "REVERSAL_EXIT", "REVERSAL_ENTRY"]
        assert all(o.state == OrderState.FILLED for o in orders)
        assert old_position.sl_state == "CLOSED"
        assert old_position.position_id not in env.sl_monitor.armed_ids()
        assert paired_entry.metadata["trigger_state"] == "FIRED"

        new_position = env.position_manager.open_positions[0]
        assert new_position.position_id != old_position.position_id
        assert not new_position.is_long
        assert new_position.sl_state == "ARMED"
        assert env.sl_monitor.armed_ids() == [new_position.position_id]
        assert len(reversal_alerts) == 1
        assert reversal_alerts[0]["old_side"] == "LONG"
        assert reversal_alerts[0]["new_side"] == "SHORT"
        assert reversal_alerts[0]["status"] == "COMPLETE"
        assert reversal_alerts[0]["stop_price"] == new_position.stop_price

        # The new short's own stop creates one ordinary exit and closes only
        # its owning position; the old long stop cannot be inherited.
        stop_exit = engine._evaluate_position_sl(
            env, new_position, new_position.stop_price + 1, "live")
        assert stop_exit is not None
        orders = list(env.execution_engine._orders.values())
        assert len(orders) == 4
        assert orders[-1].order_role == "EXIT"
        assert orders[-1].state == OrderState.FILLED
        assert not env.position_manager.open_positions
        assert not env.sl_monitor.armed_ids()

        # After the SL exit is broker-confirmed flat, a distinct BUY signal
        # with the same DEMA context can arm a new candle trigger and create a
        # new position/SL. The prior signal ID and stop owner stay retired.
        strategy._prev_fast_close = 100.0
        strategy._prev_htf_value = 100.0
        strategy._prev_fast_high = 103.0
        strategy._prev_fast_low = 99.0
        _live_price(engine, env, broker, 101.0)
        next_entry = strategy.on_bar(
            Bar("GOLDM", "15m", 5, 6, 100, 105, 99, 101, 1),
            SimpleNamespace(htf_value=100.0), 100.0)
        assert next_entry is not None
        assert next_entry.signal_id != entry.signal_id
        assert next_entry.metadata["signal_htf_dema_atr"] == entry.metadata["signal_htf_dema_atr"]
        assert next_entry.metadata["trigger_state"] == "ARMED"
        engine._process_signal(next_entry, "live")
        assert len(env.execution_engine._orders) == 4
        assert strategy.on_tick(next_entry.trigger_price - 0.01, time.time()) is None
        assert strategy.on_tick(next_entry.trigger_price, time.time()) is next_entry
        engine._process_signal(next_entry, "live")
        assert len(env.execution_engine._orders) == 5
        assert env.execution_engine._orders[next(reversed(env.execution_engine._orders))].state == OrderState.FILLED
        final_position = env.position_manager.open_positions[0]
        assert final_position.position_id != new_position.position_id
        assert final_position.sl_state == "ARMED"
        assert env.sl_monitor.armed_ids() == [final_position.position_id]
    finally:
        engine.stop()
        persistence.close()


def test_live_reversal_entry_retries_after_broker_position_endpoint_lags_exit_fill(tmp_path):
    """A filled reversal exit must retain and later submit its paired entry.

    Dhan may publish the exit fill before its positions endpoint reports flat.
    The first activation attempt must fail closed without losing the armed
    durable entry; a later flat confirmation must submit that entry once.
    """
    engine, env, broker, persistence = _runtime(tmp_path)
    strategy = env.strategies["gold_02"]
    try:
        entry = _long_candle_signal(engine, env, broker, strategy)
        _fire_and_submit(engine, env, broker, strategy, entry)
        old_position = env.position_manager.open_positions[0]
        assert old_position.is_long

        strategy._prev_fast_close = 100.0
        strategy._prev_htf_value = 100.0
        strategy._prev_fast_high = 103.0
        strategy._prev_fast_low = 99.0
        _live_price(engine, env, broker, 99.0)
        reversal_exit = strategy.on_bar(
            Bar("GOLDM", "15m", 3, 4, 100, 101, 96, 99, 1),
            SimpleNamespace(htf_value=100.0), 100.0)
        assert reversal_exit is not None
        paired_entry = strategy.pending_entry.signal
        engine._process_signal(reversal_exit, "live")
        _live_price(engine, env, broker, reversal_exit.trigger_price)
        assert strategy.on_tick(reversal_exit.trigger_price, time.time()) is reversal_exit

        # Simulate the broker's positions endpoint lagging an already-confirmed
        # exit fill. The close must be applied locally, while the reversal leg
        # remains durably armed and no overlapping entry is submitted yet.
        actual_positions = broker.positions
        broker.positions = lambda: [{
            "strategy_id": "gold_02", "instrument": "GOLDM",
            "side": "LONG", "quantity": 1,
        }]
        engine._process_signal(reversal_exit, "live")
        orders = list(env.execution_engine._orders.values())
        assert [order.order_role for order in orders] == ["ENTRY", "REVERSAL_EXIT"]
        assert not env.position_manager.open_positions
        assert strategy.pending_entry is not None
        assert strategy.pending_entry.signal is paired_entry
        assert strategy.pending_entry.status == "waiting_for_flat"

        # Once broker position state catches up, the retry path must send the
        # paired opposite entry exactly once through the normal live pipeline.
        broker.positions = actual_positions
        # Exercise the real periodic reconciliation hook that retries parked
        # reversal entries after Dhan's position endpoint catches up.
        engine._reconcile_strategy_positions("live")
        orders = list(env.execution_engine._orders.values())
        assert [order.order_role for order in orders] == [
            "ENTRY", "REVERSAL_EXIT", "REVERSAL_ENTRY"]
        assert orders[-1].entry_signal_id == paired_entry.signal_id
        assert orders[-1].state == OrderState.FILLED
        assert strategy.pending_entry is None
        new_position = env.position_manager.open_positions[0]
        assert new_position.is_open and not new_position.is_long
        assert new_position.sl_state == "ARMED"
    finally:
        engine.stop()
        persistence.close()


def test_new_reversal_replaces_parked_entry_while_flat_query_is_in_flight(tmp_path):
    """A slow broker-flat read must not submit a superseded reversal entry."""
    engine, env, broker, persistence = _runtime(tmp_path)
    strategy = env.strategies["gold_02"]
    try:
        old_signal = _long_candle_signal(engine, env, broker, strategy)
        old_signal.side = "SHORT"
        old_signal.metadata["is_reversal_entry"] = True
        old_pending = PendingEntry(
            signal=old_signal, trigger_price=old_signal.trigger_price,
            side="SHORT", status="waiting_for_flat")
        strategy.pending_entry = old_pending
        processed = []
        engine._process_signal = lambda signal, env_name=None: processed.append(signal)

        # Simulate the market callback replacing the pending reversal during
        # the REST position query. The broker query itself is outside the
        # engine lock, and the post-query ownership check must reject the old
        # candidate instead of firing it over the newer signal.
        newer_signal = _long_candle_signal(
            engine, env, broker, strategy, start=3, high=105)
        newer_signal.side = "SHORT"
        newer_signal.metadata["is_reversal_entry"] = True
        newer_pending = PendingEntry(
            signal=newer_signal, trigger_price=newer_signal.trigger_price,
            side="SHORT", status="waiting_for_flat")

        def broker_flat_replaces_pending(_env, _signal):
            with engine._lock:
                strategy.pending_entry = newer_pending
            return True, {"positions": []}

        engine._broker_flat_for_entry = broker_flat_replaces_pending
        assert engine._activate_reversal_entry_after_flat(env, "gold_02") is False
        assert strategy.pending_entry is newer_pending
        assert strategy.pending_entry.signal is newer_signal
        assert strategy.pending_entry.status == "waiting_for_flat"
        assert processed == []
    finally:
        engine.stop()
        persistence.close()


def test_reversal_entry_waits_for_environment_reconciliation_then_submits(tmp_path):
    """A confirmed-flat reversal survives a closed startup-reconciliation gate."""
    engine, env, broker, persistence = _runtime(tmp_path)
    strategy = env.strategies["gold_02"]
    try:
        initial = _long_candle_signal(engine, env, broker, strategy)
        _fire_and_submit(engine, env, broker, strategy, initial)
        strategy._prev_fast_close = 100.0
        strategy._prev_htf_value = 100.0
        strategy._prev_fast_high = 103.0
        strategy._prev_fast_low = 99.0
        _live_price(engine, env, broker, 99.0)
        reversal_exit = strategy.on_bar(
            Bar("GOLDM", "15m", 3, 4, 100, 101, 96, 99, 1),
            SimpleNamespace(htf_value=100.0), 100.0)
        assert reversal_exit is not None
        paired_entry = strategy.pending_entry.signal
        engine._process_signal(reversal_exit, "live")
        _live_price(engine, env, broker, reversal_exit.trigger_price)
        assert strategy.on_tick(reversal_exit.trigger_price, time.time()) is reversal_exit

        # Model the live failure: Dhan has confirmed the old position flat,
        # but the environment-wide reconcile flag is still closed.
        engine._reconciled_envs.discard("live")
        engine._process_signal(reversal_exit, "live")
        assert [o.order_role for o in env.execution_engine._orders.values()] == [
            "ENTRY", "REVERSAL_EXIT"]
        assert not env.position_manager.open_positions
        assert strategy.pending_entry is not None
        assert strategy.pending_entry.signal is paired_entry
        assert strategy.pending_entry.status == "waiting_for_flat"
        assert paired_entry.metadata["trigger_state"] == "ARMED"
        durable = next(row for row in persistence.get_pending_orders(
            execution_mode="LIVE") if row.get("signal_id") == paired_entry.signal_id)
        assert durable["status"] == "armed"

        # The normal periodic reconcile reopens the gate and retries the same
        # paired signal exactly once through the standard order/fill/SL flow.
        engine._reconcile_strategy_positions("live")
        orders = list(env.execution_engine._orders.values())
        assert [o.order_role for o in orders] == [
            "ENTRY", "REVERSAL_EXIT", "REVERSAL_ENTRY"]
        assert orders[-1].entry_signal_id == paired_entry.signal_id
        assert orders[-1].state == OrderState.FILLED
        assert strategy.pending_entry is None
        position = env.position_manager.open_positions[0]
        assert position.is_open and not position.is_long
        assert position.sl_state == "ARMED"
        assert env.sl_monitor.armed_ids() == [position.position_id]
    finally:
        engine.stop()
        persistence.close()


def test_reversal_entry_survives_stale_feed_gate_and_retries_after_recovery(tmp_path):
    """A temporary feed-health block parks, then retries the same paired entry."""
    engine, env, broker, persistence = _runtime(tmp_path)
    strategy = env.strategies["gold_02"]
    try:
        signal = _long_candle_signal(engine, env, broker, strategy)
        signal.side = "SHORT"
        signal.signal_type = SignalType.SHORT
        signal.metadata.update({
            "is_reversal": True,
            "is_reversal_entry": True,
            "pending": False,
            "triggered": True,
            "trigger_state": "FIRED",
            "reversal_entry_trigger_level": signal.trigger_price,
        })
        engine._arm_live_pending(signal, env)
        strategy.pending_entry = None
        engine.market_data_health.mark_unhealthy("GOLDM")

        engine._process_signal(signal, "live")
        assert not env.execution_engine._orders
        assert strategy.pending_entry is not None
        assert strategy.pending_entry.signal is signal
        assert strategy.pending_entry.status == "waiting_for_flat"
        row = persistence.get_pending_order(signal.signal_id, execution_mode="LIVE")
        assert row["status"] == "armed"
        assert row["trigger_source"] == "reversal_entry_wait:market_data_unhealthy"

        # Recovery uses the normal broker reconciliation and ordinary order path.
        _live_price(engine, env, broker, 102.0)
        engine._reconcile_strategy_positions("live")
        orders = list(env.execution_engine._orders.values())
        assert [order.order_role for order in orders] == ["REVERSAL_ENTRY"]
        assert orders[0].state == OrderState.FILLED
        assert env.position_manager.open_positions[0].side == PositionSide.SHORT
    finally:
        engine.stop()
        persistence.close()


def test_historical_rejection_poll_cannot_erase_fired_gold_entry_before_submit(tmp_path):
    """Reproduce the live poller race that rejected GOLDM before Dhan POST.

    The new trigger has fired and ``pending_entry`` is None, while an old
    rejected order remains in the execution book. Polling that old order must
    not clear the new signal's fired ownership before SignalFlow submits it.
    """
    engine, env, broker, persistence = _runtime(tmp_path)
    strategy = env.strategies["gold_02"]
    try:
        signal = _long_candle_signal(engine, env, broker, strategy)
        engine._process_signal(signal, "live")

        old_terminal = SimpleNamespace(
            order_id="LIVE-OLD-REJECTED",
            strategy_id="gold_02",
            state=OrderState.REJECTED,
            order_role="ENTRY",
            entry_signal_id="old-signal-id",
            parent_signal_id="old-signal-id",
            trade_id="old-trade-id",
        )
        env.execution_engine._orders[old_terminal.order_id] = old_terminal

        _live_price(engine, env, broker, signal.trigger_price)
        fired = strategy.on_tick(signal.trigger_price, time.time())
        assert fired is signal
        assert strategy.pending_entry is None
        assert strategy.is_fired_trigger_signal(signal.signal_id)

        # Run the actual poller order cycle in the narrow tick -> submit gap.
        broker.order_statuses = lambda: {"unrelated-terminal": {}}
        poller = LiveBrokerPoller(env, config=engine.config)
        poller._terminalize_pending_from_broker = lambda _statuses: None
        poller._release_terminal_exits = lambda: 0
        poller._persist_order_state = lambda _order: None
        poller._settle_terminal_entry_lifecycle = lambda _order: None
        poller._terminalize_pending_entries = lambda *_args: None
        poller._terminalize_pending_from_broker = lambda *_args: None
        env.execution_engine.apply_broker_statuses = lambda _statuses: []
        poller.poll_orders()

        assert strategy.is_fired_trigger_signal(signal.signal_id)
        engine._process_signal(fired, "live")

        submitted = [
            order for order in env.execution_engine._orders.values()
            if getattr(order, "entry_signal_id", None) == signal.signal_id
        ]
        assert len(submitted) == 1
        assert submitted[0].state == OrderState.FILLED
        assert submitted[0]._broker_order_id
        assert broker._orders
        position = env.position_manager.open_positions[0]
        assert position.is_long and position.sl_state == "ARMED"
    finally:
        engine.stop()
        persistence.close()


def test_poller_reset_rechecks_order_ownership_under_engine_lock(tmp_path):
    """A newer trigger arriving after poller classification must win atomically."""
    engine, env, broker, persistence = _runtime(tmp_path)
    strategy = env.strategies["gold_02"]
    try:
        current = _long_candle_signal(engine, env, broker, strategy)
        engine._process_signal(current, "live")
        engine._start_live_pollers()
        assert env.sync_service._poller._state_lock is engine._lock
        reset = env.sync_service._poller._reset_strategy_fn

        # This reproduces the time-of-check/time-of-use window: the poller had
        # classified an older rejected signal as a terminal entry, then a new
        # signal became the strategy's owner before reset acquired the engine
        # lock. The callback must refuse the stale reset.
        assert reset("gold_02", signal_id="older-signal",
                     trade_id="older-trade") is False
        assert strategy.pending_entry.signal is current
        assert strategy.state.value.startswith("pending")
        assert reset("gold_02", signal_id=current.signal_id) is True
        assert strategy.pending_entry is None
    finally:
        engine.stop()
        persistence.close()


def test_live_poller_fill_and_strategy_reset_share_engine_lock(tmp_path):
    """Broker fills and resets serialize with the trigger-to-submit path."""
    engine, env, _broker, persistence = _runtime(tmp_path)
    try:
        engine.config._config["live"]["order_ws"]["enabled"] = False
        engine._start_live_pollers()
        poller = env.sync_service._poller
        entered = {"fill": threading.Event(), "reconcile": threading.Event()}
        engine._handle_fill = lambda *_args, **_kwargs: entered["fill"].set()
        strategy = env.strategies["gold_02"]
        strategy._register_fired_trigger("trigger-to-preserve")
        entered["reset"] = threading.Event()
        def reset_strategy():
            engine._reset_strategy_state("gold_02", env_name="live")
            entered["reset"].set()

        for label, callback in (
                ("fill", lambda: poller._handle_fill(None, "gold_02", False)),
                ("reset", reset_strategy)):
            with engine._lock:
                worker = threading.Thread(target=callback, daemon=True)
                worker.start()
                assert not entered[label].wait(0.05)
                if label == "reset":
                    assert strategy.is_fired_trigger_signal("trigger-to-preserve")
            worker.join(timeout=1)
            assert entered[label].is_set()
    finally:
        engine.stop()
        persistence.close()


def test_live_candle_trigger_fill_stop_and_reconciliation_race_in_parallel(tmp_path):
    """Stress the live callback graph with trigger/poller/SL work in parallel.

    Uses only the funded in-memory broker. Each phase launches concurrent
    duplicate market callbacks alongside order, position, account, and
    reconciliation polling; assertions inspect the final lifecycle invariants,
    not the particular thread that wins the engine lock.
    """
    engine, env, broker, persistence = _runtime(tmp_path)
    strategy = env.strategies["gold_02"]
    errors = []
    try:
        engine._running = True
        signal = _long_candle_signal(engine, env, broker, strategy)
        engine._process_signal(signal, "live")
        _live_price(engine, env, broker, signal.trigger_price)

        poller = LiveBrokerPoller(
            env, config=engine.config,
            handle_fill=lambda fill, sid, is_exit: engine._handle_fill(
                fill, sid, is_exit=is_exit, env_name="live"),
            on_reconcile=lambda: engine._reconcile_strategy_positions("live"),
            state_lock=engine._lock,
        )
        tick_handler = engine._make_tick_handler(strategy, "live")
        tick_event = SimpleNamespace(
            instrument="GOLDM", ltp=signal.trigger_price, timestamp=time.time())
        replacement_signals = []

        def completed_retest_candles():
            # A completed candle first retests the DEMA, then crosses above it
            # again with a newer high. It replaces the still-armed trigger if
            # the tick callback has not already fired that original trigger.
            for bar in (
                    Bar("GOLDM", "15m", 3, 4, 101, 102, 99, 100, 1),
                    Bar("GOLDM", "15m", 4, 5, 100, 105, 99, 101, 1)):
                with engine._lock:
                    replacement = strategy.on_bar(
                        bar, SimpleNamespace(htf_value=100.0), 100.0)
                    if replacement is not None:
                        replacement_signals.append(replacement)
                        engine._bind_signal_position(
                            replacement, strategy, "live")
                        engine._process_signal(replacement, "live")

        def run_parallel(callbacks):
            barrier = threading.Barrier(len(callbacks))

            def invoke(callback):
                try:
                    barrier.wait(timeout=3)
                    callback()
                except BaseException as exc:  # retain worker failures for assertions
                    errors.append(exc)

            with ThreadPoolExecutor(max_workers=len(callbacks)) as pool:
                futures = [pool.submit(invoke, cb) for cb in callbacks]
                for future in futures:
                    future.result(timeout=8)

        entry_callbacks = [lambda: tick_handler(tick_event) for _ in range(8)]
        entry_callbacks += [poller.poll_orders for _ in range(3)]
        entry_callbacks += [poller.poll_positions for _ in range(2)]
        entry_callbacks += [poller.poll_reconcile for _ in range(2)]
        entry_callbacks += [poller.poll_account]
        entry_callbacks.append(completed_retest_candles)
        run_parallel(entry_callbacks)
        assert not errors

        entry_orders = [order for order in env.execution_engine._orders.values()
                        if getattr(order, "order_role", "").upper()
                        in ("ENTRY", "FALLBACK_MARKET")]
        if not entry_orders:
            # The candle replacement won the lock race; the concurrent 103
            # tick correctly stayed below its newer 105 trigger. Fire that
            # owner now so the remainder of this test covers its full fill/SL
            # lifecycle as well.
            assert replacement_signals
            active = strategy.pending_entry
            assert active is not None
            assert active.signal is replacement_signals[-1]
            assert active.trigger_price == 105.0
            _live_price(engine, env, broker, active.trigger_price)
            replacement_tick = SimpleNamespace(
                instrument="GOLDM", ltp=active.trigger_price,
                timestamp=time.time())
            tick_handler(replacement_tick)
            entry_orders = [order for order in env.execution_engine._orders.values()
                            if getattr(order, "order_role", "").upper()
                            in ("ENTRY", "FALLBACK_MARKET")]
        assert len(entry_orders) == 1
        assert entry_orders[0].state == OrderState.FILLED
        assert len(env.position_manager.open_positions) == 1
        position = env.position_manager.open_positions[0]
        assert position.is_open and position.sl_state == "ARMED"
        assert env.sl_monitor.armed_ids() == [position.position_id]

        # Dhan WS health is represented by a deterministic connected feed;
        # every concurrent stop tick is valid and crosses this position's own
        # stop. Pollers race the same close and must not create another exit.
        engine.data_adapter.ws = SimpleNamespace(
            connected=True, _last_tick_time=time.time(), _stats={"tick": 0},
            is_stale=lambda: False)
        stop_tick = {
            "instrument": "GOLDM", "ltp": position.stop_price - 1.0,
            "event_timestamp": time.time(), "receive_timestamp": time.time(),
            "volume": 1,
        }
        exit_callbacks = [lambda: engine._on_tick(stop_tick) for _ in range(8)]
        exit_callbacks += [poller.poll_orders for _ in range(3)]
        exit_callbacks += [poller.poll_positions for _ in range(2)]
        exit_callbacks += [poller.poll_reconcile for _ in range(2)]
        exit_callbacks += [poller.poll_account]
        run_parallel(exit_callbacks)
        assert not errors

        exit_orders = [order for order in env.execution_engine._orders.values()
                       if getattr(order, "order_role", "").upper() == "EXIT"]
        assert len(exit_orders) == 1
        assert exit_orders[0].state == OrderState.FILLED
        assert not env.position_manager.open_positions
        assert not env.sl_monitor.armed_ids()
        assert strategy.state.value == "flat"
        assert not poller._last_position_report
    finally:
        engine._running = False
        engine.stop()
        persistence.close()


def test_stale_flat_broker_snapshot_cannot_erase_concurrent_filled_entry(tmp_path):
    """Discard REST position truth captured before a concurrent local fill."""
    engine, env, broker, persistence = _runtime(tmp_path)
    strategy = env.strategies["gold_02"]
    query_started = threading.Event()
    release_query = threading.Event()
    result = []
    errors = []
    original_positions = broker.positions

    def delayed_flat_snapshot():
        query_started.set()
        if not release_query.wait(timeout=3):
            raise TimeoutError("test did not release delayed position response")
        return []  # stale: the test fills an entry before this response arrives

    broker.positions = delayed_flat_snapshot
    # This scenario isolates stale reconciliation. The ordinary entry path
    # must not make a second broker.positions() request through the optional
    # exit-first gate while the controlled reconciliation request is paused.
    engine.config._config["live"]["exit_first"]["enabled"] = False

    def reconcile_from_stale_response():
        try:
            result.append(engine.sync_sl_from_broker(env_name="live"))
        except BaseException as exc:
            errors.append(exc)

    worker = threading.Thread(target=reconcile_from_stale_response, daemon=True)
    try:
        worker.start()
        assert query_started.wait(timeout=2)

        signal = _long_candle_signal(engine, env, broker, strategy)
        _fire_and_submit(engine, env, broker, strategy, signal)
        position = env.position_manager.open_positions[0]
        assert position.is_open and position.sl_state == "ARMED"

        release_query.set()
        worker.join(timeout=4)
        assert not worker.is_alive()
        assert not errors
        assert result[0]["status"] == "stale_snapshot"
        assert env.position_manager.open_positions == [position]
        assert strategy.current_position_id == position.position_id
        assert position.sl_state == "ARMED"
        assert env.sl_monitor.armed_ids() == [position.position_id]
    finally:
        release_query.set()
        broker.positions = original_positions
        engine.stop()
        persistence.close()


def test_optional_auto_resolver_discards_broker_snapshot_older_than_new_fill(tmp_path):
    """The opt-in mirror resolver must apply the same stale-read guard."""
    engine, env, broker, persistence = _runtime(tmp_path)
    strategy = env.strategies["gold_02"]
    query_started = threading.Event()
    release_query = threading.Event()
    errors = []

    def delayed_flat_snapshot():
        query_started.set()
        if not release_query.wait(timeout=3):
            raise TimeoutError("test did not release delayed position response")
        return []

    broker.positions = delayed_flat_snapshot
    engine.config._config["live"]["exit_first"]["enabled"] = False

    def resolve_from_stale_response():
        try:
            engine._resolve_broker_positions(
                env, {"reconcile_auto_resolve": True})
        except BaseException as exc:
            errors.append(exc)

    worker = threading.Thread(target=resolve_from_stale_response, daemon=True)
    try:
        worker.start()
        assert query_started.wait(timeout=2)
        signal = _long_candle_signal(engine, env, broker, strategy)
        _fire_and_submit(engine, env, broker, strategy, signal)
        position = env.position_manager.open_positions[0]

        release_query.set()
        worker.join(timeout=4)
        assert not worker.is_alive()
        assert not errors
        assert env.position_manager.open_positions == [position]
        assert position.is_open and position.sl_state == "ARMED"
        assert strategy.current_position_id == position.position_id
    finally:
        release_query.set()
        engine.stop()
        persistence.close()


def test_live_restore_hydrates_db_order_when_json_snapshot_is_missing(tmp_path):
    engine, env, _broker, persistence = _runtime(tmp_path)
    try:
        persistence.save_signal({
            "signal_id": "ENTRY-DB-ONLY", "strategy_id": "gold_02",
            "instrument": "GOLDM", "side": "SHORT", "signal_type": "entry",
            "timestamp": time.time(), "trigger_price": 228000.0,
            "stop_price": 229000.0, "quantity": 1,
        })
        persistence.save_trade({
            "trade_id": "TRADE-DB-ONLY", "strategy_id": "gold_02",
            "instrument": "GOLDM", "side": "SHORT", "quantity": 1,
            "multiplier": 1.0, "entry_timestamp": time.time(),
            "entry_price": 228000.0, "status": "open", "execution_mode": "LIVE",
            "entry_signal_id": "ENTRY-DB-ONLY",
        })
        persistence.save_position(Position(
            position_id="POS-DB-ONLY", strategy_id="gold_02",
            instrument="GOLDM", side=PositionSide.SHORT, quantity=1,
            average_entry=228000.0, entry_timestamp=time.time(),
            stop_price=229000.0, trade_id="TRADE-DB-ONLY", multiplier=1.0,
            entry_signal_id="ENTRY-DB-ONLY", entry_order_id="LIVE-DB-ONLY",
            position_generation=7, sl_state="ARMED", lifecycle_id="TRADE-DB-ONLY",
        ))
        persistence.save_order({
            "order_id": "LIVE-DB-ONLY", "strategy_id": "gold_02",
            "instrument": "GOLDM", "side": "SELL", "quantity": 1,
            "order_type": "LIMIT", "price": 228000.0,
            "trigger_price": 228000.0, "state": "submitted",
            "filled_quantity": 0, "average_fill_price": 0.0,
            "signal_id": "REV-ENTRY", "trade_id": "TRADE-DB-ONLY",
            "broker_order_id": "DHAN-DB-ONLY", "order_role": "REVERSAL_ENTRY",
            "reversal_parent_signal_id": "REV-EXIT",
            "created_at": "2026-09-30T10:00:00+00:00",
            "updated_at": "2026-09-30T10:00:00+00:00",
        })
        env.execution_engine._orders.clear()

        engine.restore({}, env_name="live")

        restored = env.execution_engine.get_order("LIVE-DB-ONLY")
        assert restored is not None
        assert restored._broker_order_id == "DHAN-DB-ONLY"
        assert restored.reversal_parent_signal_id == "REV-EXIT"
        position = env.position_manager.get_position("POS-DB-ONLY")
        assert position is not None and position.is_open
        assert env.strategies["gold_02"].position_side == "SHORT"
        assert env.strategies["gold_02"].current_position_id == "POS-DB-ONLY"
    finally:
        engine.stop()
        persistence.close()


def test_fresh_runtime_limit_to_market_fallback_requires_cancel_confirmation(tmp_path):
    """Real engine + watcher flow; broker accepts LIMIT asynchronously.

    The LIMIT must be authoritatively cancelled before a new MARKET is sent;
    the market fill then enters the same fill/position/SL pipeline.
    """
    broker = _FundedStubBroker(defer_fills=True)
    engine, env, broker, persistence = _runtime(tmp_path, broker=broker)
    strategy = env.strategies["gold_02"]
    watcher = _watcher(engine, env, broker)
    try:
        signal = _long_candle_signal(engine, env, broker, strategy)
        limit = _fire_and_submit(engine, env, broker, strategy, signal)
        assert limit.order_type == "LIMIT"
        assert limit.state == OrderState.SUBMITTED
        assert len(broker._orders) == 1
        # Once the original trigger has fired and its LIMIT is at the broker,
        # a later opposite candle cannot steal this order's recovery lineage.
        strategy._check_long_cross = lambda *args: False
        strategy._check_short_cross = lambda *args: True
        later = strategy.on_bar(
            Bar("GOLDM", "15m", 2, 3, 104, 105, 95, 96, 1),
            SimpleNamespace(htf_value=103.0), 103.0)
        assert later is None
        assert len(env.execution_engine._orders) == 1
        rec = watcher.register_from_order(limit)
        rec.current_market_price = 104.0
        rec.trigger_crossed = True
        result = watcher._do_market_fallback(rec, time.time())

        assert result["ok"] is True, result
        assert limit.state == OrderState.CANCELED
        assert broker._orders[limit._broker_order_id]["status"] == "cancelled"
        fallback = env.execution_engine.get_order(result["market_order_id"])
        assert fallback.order_type == "MARKET"
        assert fallback.order_role == "FALLBACK_MARKET"
        assert fallback.multiplier == 1.0  # broker order metadata remains unchanged
        assert fallback.fallback_cancel_confirmed is True
        assert fallback.original_order_id == limit.order_id
        assert fallback.quantity == limit.quantity == 1
        assert fallback.state == OrderState.SUBMITTED
        assert len(broker._orders) == 2  # cancelled LIMIT + one MARKET
        assert not env.position_manager.open_positions
        stored = persistence.get_orders(fallback.order_id)
        assert len(stored) == 1
        assert stored[0]["order_role"] == "FALLBACK_MARKET"
        assert stored[0]["original_order_id"] == limit.order_id

        watcher.register_from_order(fallback)
        assert broker.ack_order(fallback._broker_order_id, price=104.0)
        summary = watcher.verify_order(fallback.order_id, force=True)
        assert summary["fills_applied"] == 1
        assert fallback.state == OrderState.FILLED
        stored = persistence.get_orders(fallback.order_id)
        assert stored[0]["state"] == "filled"
        assert any(row["order_id"] == fallback.order_id
                   for row in persistence.get_fills())
        position = env.position_manager.open_positions[0]
        assert position.quantity == 1
        assert position.sl_state == "ARMED"
        assert env.sl_monitor.armed_ids() == [position.position_id]
    finally:
        engine.stop()
        persistence.close()


def test_fresh_runtime_partial_market_fallback_protects_actual_filled_qty(tmp_path):
    broker = _FundedStubBroker(defer_fills=True)
    engine, env, broker, persistence = _runtime(
        tmp_path, quantity=2, broker=broker)
    strategy = env.strategies["gold_02"]
    watcher = _watcher(engine, env, broker)
    emitted = []
    original_publish = engine.publish_event
    engine.publish_event = lambda kind, data, **kwargs: (
        emitted.append((kind, dict(data))), original_publish(kind, data, **kwargs))
    try:
        signal = _long_candle_signal(engine, env, broker, strategy)
        limit = _fire_and_submit(engine, env, broker, strategy, signal)
        rec = watcher.register_from_order(limit)
        rec.current_market_price = 104.0
        result = watcher._do_market_fallback(rec, time.time())
        assert result["ok"] is True
        assert result["quantity"] == 2
        fallback = env.execution_engine.get_order(result["market_order_id"])
        watcher.register_from_order(fallback)

        assert broker.ack_partial_order(
            fallback._broker_order_id, quantity=1, price=104.0)
        summary = watcher.verify_order(fallback.order_id, force=True)
        assert summary["fills_applied"] == 1
        assert fallback.state == OrderState.PARTIALLY_FILLED
        position = env.position_manager.open_positions[0]
        assert position.quantity == 1
        assert position.sl_state == "ARMED"
        assert env.sl_monitor.armed_ids() == [position.position_id]
        underfill = [data for kind, data in emitted
                     if kind == "entry_quantity_underfilled"]
        assert len(underfill) == 1
        assert underfill[0]["requested_quantity"] == 2
        assert underfill[0]["filled_position_quantity"] == 1
        # The watcher never retries the missing quantity after its one market
        # order; the only orders are the cancelled LIMIT and one MARKET.
        assert len(env.execution_engine._orders) == 2
        assert len(broker._orders) == 2
    finally:
        engine.stop()
        persistence.close()


def test_fresh_runtime_sl_exit_limit_fallback_closes_only_after_broker_fill(tmp_path):
    """Exercise position-owned SL -> LIMIT EXIT -> confirmed cancel -> MARKET."""
    broker = _FundedStubBroker(defer_fills=True)
    engine, env, broker, persistence = _runtime(tmp_path, broker=broker)
    strategy = env.strategies["gold_02"]
    watcher = _watcher(engine, env, broker)
    try:
        signal = _long_candle_signal(engine, env, broker, strategy)
        entry = _fire_and_submit(engine, env, broker, strategy, signal)
        watcher.register_from_order(entry)
        assert broker.ack_order(entry._broker_order_id, price=103.0)
        assert watcher.verify_order(entry.order_id, force=True)["fills_applied"] == 1
        position = env.position_manager.open_positions[0]
        assert position.sl_state == "ARMED"
        old_sl_id = position.position_id

        stop_signal = engine._evaluate_position_sl(
            env, position, position.stop_price - 1, "live")
        assert stop_signal is not None
        exit_limit = list(env.execution_engine._orders.values())[-1]
        assert exit_limit.order_role == "EXIT"
        assert exit_limit.order_type == "LIMIT"
        assert exit_limit.state == OrderState.SUBMITTED
        assert position.position_id in env.sl_monitor.armed_ids()

        rec = watcher.register_from_order(exit_limit)
        rec.current_market_price = position.stop_price - 1
        result = watcher._do_market_fallback(rec, time.time())
        assert result["ok"] is True, result
        assert exit_limit.state == OrderState.CANCELED
        market_exit = env.execution_engine.get_order(result["market_order_id"])
        assert market_exit.order_role == "EXIT"
        assert market_exit.order_type == "MARKET"
        assert market_exit.multiplier == 1.0  # close P&L resolves from the position
        assert market_exit.fallback_cancel_confirmed is True
        assert market_exit.original_order_id == exit_limit.order_id
        # Local exposure and its stop stay present until Dhan confirms the
        # fallback fill; cancel confirmation alone must not mark it flat.
        assert env.position_manager.open_positions[0].position_id == old_sl_id
        assert old_sl_id in env.sl_monitor.armed_ids()

        watcher.register_from_order(market_exit)
        assert broker.ack_order(market_exit._broker_order_id, price=97.0)
        # Dhan can report flat as soon as this MARKET fill happens, a few
        # milliseconds before the order watcher routes its fill. Reconciliation
        # must retain the position because the cancelled LIMIT's owned child is
        # already FILLED.
        sync = engine.sync_sl_from_broker(env_name="live")
        assert sync["status"] == "reconciled"
        assert env.position_manager.open_positions[0].position_id == old_sl_id
        assert env.position_manager.open_positions[0].sl_state == "EXITING"
        summary = watcher.verify_order(market_exit.order_id, force=True)
        assert summary["fills_applied"] == 1
        assert market_exit.state == OrderState.FILLED
        assert not env.position_manager.open_positions
        assert old_sl_id not in env.sl_monitor.armed_ids()
        closed_trade = next(t for t in persistence.get_trades("gold_02")
                            if t.get("trade_id") == position.trade_id)
        assert closed_trade["multiplier"] == position.multiplier
        assert closed_trade["gross_pnl"] == (97.0 - 103.0) * position.quantity * position.multiplier
        trade = env.runtimes.require("gold_02").lifecycle.get_trade(
            position.trade_id)
        assert str(trade.status).upper() in ("CLOSED", "COMPLETED")
    finally:
        engine.stop()
        persistence.close()


def test_fresh_runtime_stale_sl_fallback_fill_recovers_exact_open_trade(tmp_path):
    """Recover the exact SL fallback if flat reconciliation already dropped it."""
    broker = _FundedStubBroker(defer_fills=True)
    engine, env, broker, persistence = _runtime(tmp_path, broker=broker)
    strategy = env.strategies["gold_02"]
    watcher = _watcher(engine, env, broker)
    try:
        signal = _long_candle_signal(engine, env, broker, strategy)
        entry = _fire_and_submit(engine, env, broker, strategy, signal)
        watcher.register_from_order(entry)
        assert broker.ack_order(entry._broker_order_id, price=103.0)
        assert watcher.verify_order(entry.order_id, force=True)["fills_applied"] == 1
        position = env.position_manager.open_positions[0]
        engine._evaluate_position_sl(env, position, position.stop_price - 1, "live")
        exit_limit = position and env.execution_engine.get_order(
            position.exit_order_id)
        rec = watcher.register_from_order(exit_limit)
        rec.current_market_price = position.stop_price - 1
        fallback_result = watcher._do_market_fallback(rec, time.time())
        assert fallback_result["ok"] is True
        market_exit = env.execution_engine.get_order(
            fallback_result["market_order_id"])
        watcher.register_from_order(market_exit)
        assert broker.ack_order(market_exit._broker_order_id, price=97.0)

        # Simulate the precise production race: local broker-position sync has
        # removed the memory owner, while durable trade/position rows remain
        # open and the exact fallback fill is now available from Dhan.
        env.position_manager.abandon_stale_position(position.position_id)
        assert not env.position_manager.open_positions
        summary = watcher.verify_order(market_exit.order_id, force=True)
        assert summary["fills_applied"] == 1
        assert not env.position_manager.open_positions
        trade = env.runtimes.require("gold_02").lifecycle.get_trade(
            position.trade_id)
        assert str(trade.status).upper() in ("CLOSED", "COMPLETED")
        assert not persistence.get_open_positions("gold_02")
        durable_trade = next(t for t in persistence.get_trades("gold_02")
                             if t.get("trade_id") == position.trade_id)
        assert str(durable_trade.get("status", "")).upper() in (
            "CLOSED", "COMPLETED")
        exit_fill_count = len([row for row in persistence.get_fills()
                               if row.get("order_id") == market_exit.order_id])
        engine._handle_fill(
            env.execution_engine.get_fills(
                strategy_id="gold_02", instrument="GOLDM")[-1],
            None, is_exit=True, env_name="live")
        assert len([row for row in persistence.get_fills()
                    if row.get("order_id") == market_exit.order_id]) == exit_fill_count == 1
        quarantines = persistence.get_quarantine_records(limit=200)
        assert not any("stale_lifecycle_fill_rejected" in str(q.get("reason", ""))
                       or "stale_lifecycle_fill_rejected"
                       in str(q.get("payload", "")) for q in quarantines)
    finally:
        engine.stop()
        persistence.close()


def test_fresh_runtime_newer_reversal_replaces_both_old_triggers_and_lineage(tmp_path):
    """An untriggered reversal is replaced by the latest candle/DEMA pair."""
    engine, env, broker, persistence = _runtime(tmp_path)
    strategy = env.strategies["gold_02"]
    try:
        long_signal = _long_candle_signal(engine, env, broker, strategy)
        long_entry = _fire_and_submit(engine, env, broker, strategy, long_signal)
        assert long_entry.state == OrderState.FILLED
        old_position = env.position_manager.open_positions[0]

        strategy._check_short_cross = lambda *args: True
        strategy._check_long_cross = lambda *args: False
        _live_price(engine, env, broker, 99.0)
        old_exit = strategy.on_bar(
            Bar("GOLDM", "15m", 3, 4, 100, 101, 96, 99, 1),
            SimpleNamespace(htf_value=100.0), 100.0)
        assert old_exit is not None
        old_entry = strategy.pending_entry.signal
        assert old_exit.metadata["signal_htf_dema_atr"] == 100.0
        assert old_exit.parent_position_id == old_position.position_id
        assert old_exit.lifecycle_id == old_position.trade_id
        engine._process_signal(old_exit, "live")

        _live_price(engine, env, broker, 97.0)
        new_exit = strategy.on_bar(
            Bar("GOLDM", "15m", 4, 5, 99, 100, 90, 95, 1),
            SimpleNamespace(htf_value=105.0), 105.0)
        assert new_exit is not None
        assert new_exit.signal_id != old_exit.signal_id
        assert new_exit.trigger_price != old_exit.trigger_price
        assert new_exit.metadata["signal_candle_low"] == 90
        assert new_exit.metadata["signal_htf_dema_atr"] == 105.0
        new_entry = strategy.pending_entry.signal
        assert new_entry.signal_id != old_entry.signal_id
        assert new_entry.metadata["signal_htf_dema_atr"] == 105.0
        assert old_exit.metadata["trigger_state"] == "CANCELLED"
        assert old_entry.metadata["trigger_state"] == "CANCELLED"
        assert not any(o.order_role == "REVERSAL_EXIT"
                       for o in env.execution_engine._orders.values())
        engine._process_signal(new_exit, "live")

        # The old reversal's tick cannot fire the replacement trigger.
        assert strategy.on_tick(old_exit.trigger_price, time.time()) is None
        _live_price(engine, env, broker, new_exit.trigger_price)
        fired_exit = strategy.on_tick(new_exit.trigger_price, time.time())
        assert fired_exit is new_exit
        engine._process_signal(fired_exit, "live")
        orders = list(env.execution_engine._orders.values())
        assert [o.order_role for o in orders] == [
            "ENTRY", "REVERSAL_EXIT", "REVERSAL_ENTRY"]
        assert all(o.state == OrderState.FILLED for o in orders)
        assert old_position.sl_state == "CLOSED"
        assert old_position.position_id not in env.sl_monitor.armed_ids()
        new_position = env.position_manager.open_positions[0]
        assert not new_position.is_long
        assert new_position.sl_state == "ARMED"
        assert new_position.stop_price == new_entry.stop_price
        assert env.sl_monitor.armed_ids() == [new_position.position_id]
    finally:
        engine.stop()
        persistence.close()


def test_fresh_runtime_manual_broker_close_retires_position_sl_and_reversal(tmp_path):
    """A flat snapshot without an exit fill is unresolved, never a fake close."""
    engine, env, broker, persistence = _runtime(tmp_path)
    strategy = env.strategies["gold_02"]
    try:
        signal = _long_candle_signal(engine, env, broker, strategy)
        entry = _fire_and_submit(engine, env, broker, strategy, signal)
        position = env.position_manager.open_positions[0]
        assert position.sl_state == "ARMED"

        strategy._check_short_cross = lambda *args: True
        strategy._check_long_cross = lambda *args: False
        reversal = strategy.on_bar(
            Bar("GOLDM", "15m", 3, 4, 100, 101, 96, 99, 1),
            SimpleNamespace(htf_value=101.0), 101.0)
        assert reversal is not None
        parked_entry = strategy.pending_entry.signal
        engine._process_signal(reversal, "live")
        assert position.position_id in env.sl_monitor.armed_ids()

        # Simulate an operator closing the exposure in Dhan, outside this app.
        broker._net_positions["GOLDM"] = 0
        summary = engine.sync_sl_from_broker(env_name="live")
        assert summary["status"] == "protection_incomplete"
        assert env.position_manager.open_positions == [position]
        assert position.is_open
        assert position.sl_state == "SL_UNAVAILABLE"
        assert position.position_id not in env.sl_monitor.armed_ids()
        assert strategy.pending_entry is not None
        assert strategy.pending_entry.signal is parked_entry
        assert strategy.pending_exit_trigger is not None
        assert strategy.position_side == "LONG"
        assert parked_entry.metadata["trigger_state"] != "CANCELLED"
        retry_signal = strategy.on_tick(reversal.trigger_price, time.time())
        assert retry_signal is not None
        # The pending trigger may fire, but the failed reconciliation must
        # block the resulting live order until ownership is broker-confirmed.
        engine._process_signal(retry_signal, "live")
        # Reconciliation is not a new signal and must not submit another entry.
        assert len(env.execution_engine._orders) == 1
    finally:
        engine.stop()
        persistence.close()


def test_fresh_runtime_limit_fill_race_does_not_send_duplicate_market(tmp_path):
    class FillDuringCancelBroker(_FundedStubBroker):
        def cancel_order(self, broker_order_id):
            # Model the exchange fill winning a race with the cancel request.
            self.ack_order(broker_order_id, price=104.0)
            return {"ok": False, "status": "filled"}

    broker = FillDuringCancelBroker(defer_fills=True)
    engine, env, broker, persistence = _runtime(tmp_path, broker=broker)
    strategy = env.strategies["gold_02"]
    watcher = _watcher(engine, env, broker)
    try:
        signal = _long_candle_signal(engine, env, broker, strategy)
        limit = _fire_and_submit(engine, env, broker, strategy, signal)
        rec = watcher.register_from_order(limit)
        rec.current_market_price = 104.0
        result = watcher._do_market_fallback(rec, time.time())
        assert result["ok"] is False
        assert len(broker._orders) == 1
        assert limit.state == OrderState.SUBMITTED  # unresolved until REST

        summary = watcher.verify_order(limit.order_id, force=True)
        assert summary["fills_applied"] == 1
        assert limit.state == OrderState.FILLED
        assert len(env.execution_engine._orders) == 1
        position = env.position_manager.open_positions[0]
        assert position.quantity == 1
        assert position.sl_state == "ARMED"
        assert env.sl_monitor.armed_ids() == [position.position_id]
    finally:
        engine.stop()
        persistence.close()


def test_fresh_runtime_newer_armed_buy_replaces_candle_dema_and_trigger(tmp_path):
    """A newer same-side signal owns the only armed trigger before firing."""
    engine, env, broker, persistence = _runtime(tmp_path)
    strategy = env.strategies["gold_02"]
    try:
        first = _long_candle_signal(engine, env, broker, strategy)
        engine._process_signal(first, "live")
        assert not env.execution_engine._orders

        # Make a second confirmed crossover deterministic while retaining the
        # real StrategyInstance candle/trigger creation and engine processing.
        strategy._check_long_cross = lambda *args: True
        strategy._check_short_cross = lambda *args: False
        _live_price(engine, env, broker, 102.0)
        newer = strategy.on_bar(
            Bar("GOLDM", "15m", 2, 3, 101, 108, 100, 104, 1),
            SimpleNamespace(htf_value=105.0), 105.0)
        assert newer is not None
        engine._process_signal(newer, "live")
        assert newer.signal_id != first.signal_id
        assert newer.trigger_price == 108
        assert newer.stop_price == 99  # lower current/previous candle low
        assert newer.metadata["signal_htf_dema_atr"] == 105.0
        assert newer.metadata["signal_candle_high"] == 108
        assert first.metadata["trigger_state"] == "CANCELLED"
        assert strategy.pending_entry.signal is newer
        assert not env.execution_engine._orders

        assert strategy.on_tick(first.trigger_price, time.time()) is None
        assert strategy.on_tick(newer.trigger_price - 0.01, time.time()) is None
        assert strategy.on_tick(newer.trigger_price, time.time()) is newer
        engine._process_signal(newer, "live")
        assert len(env.execution_engine._orders) == 1
        order = list(env.execution_engine._orders.values())[0]
        assert order.state == OrderState.FILLED
        assert order.entry_signal_id == newer.signal_id
        position = env.position_manager.open_positions[0]
        assert position.stop_price == newer.stop_price
        assert position.sl_state == "ARMED"
    finally:
        engine.stop()
        persistence.close()


def test_fresh_runtime_market_fallback_is_blocked_when_cancel_is_unconfirmed(tmp_path):
    class UncertainCancelBroker(_FundedStubBroker):
        def cancel_order(self, broker_order_id):
            return {"ok": False, "status": "unknown"}

    broker = UncertainCancelBroker(defer_fills=True)
    engine, env, broker, persistence = _runtime(tmp_path, broker=broker)
    strategy = env.strategies["gold_02"]
    failures = []
    watcher = _watcher(engine, env, broker, failures)
    try:
        signal = _long_candle_signal(engine, env, broker, strategy)
        limit = _fire_and_submit(engine, env, broker, strategy, signal)
        rec = watcher.register_from_order(limit)
        rec.current_market_price = 104.0
        result = watcher._do_market_fallback(rec, time.time())

        assert result["ok"] is False
        assert "cancel" in result["error"]
        assert limit.state == OrderState.SUBMITTED
        assert len(broker._orders) == 1  # no dangerous second order
        assert any("CANCEL" in str(event) or "cancel" in str(event).lower()
                   for event in failures)
    finally:
        engine.stop()
        persistence.close()

